#!/bin/bash
# Like git merge-base, but will take multiple commits.
# Doesn't accept command line options yet.

case $# in
  0 ) 
    ;;
  1 )
    echo $1
    ;;
  2 )
    git merge-base $1 $2
    ;;
  * )
    new_base=`git merge-base $1 $2`
    shift
    shift
    git-multibase $new_base $@
esac
